"""added options to quiz questions

Revision ID: d88d4462cd84
Revises: 
Create Date: 2026-02-26 01:40:47.763736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88d4462cd84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_a', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('option_b', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('option_c', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('option_d', sa.Text(), nullable=False))
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('coin_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('coin_balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('option_d')
        batch_op.drop_column('option_c')
        batch_op.drop_column('option_b')
        batch_op.drop_column('option_a')

    # ### end Alembic commands ###
